### ISSUE TITLE
Add Admins

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/metalsmith-kalastatic-dot-module#3]
Kalamuna org to be the overlords and admins. :smiling_imp:

**Comment by RobLoach** [comment]
@madeofpeople Mind adding me as an admin on here, and in the npm package?

```
npm owner add robloach metalsmith-kalastatic-dot-module
```

Then I'll be able to make a release.

**Comment by thiagodemellobueno** [comment]
This has been done. Reassigning to @RobLoach
